// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewTemplateManager.Infrastructure.Persistence;

#nullable disable

namespace NewTemplateManager.Infrastructure.Migrations
{
    [DbContext(typeof(NewTemplateManagerContext))]
    partial class NewTemplateManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NewTemplateManager.Domain.Entities.SampleModel", b =>
                {
                    b.Property<string>("SampleModelName")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("char(36)");

                    b.HasKey("SampleModelName");

                    b.ToTable("SampleModels");
                });
#pragma warning restore 612, 618
        }
    }
}
