version: '3.1'
services:
  newtemplatemanager_api:
    #image: oladeji1/newtemplatemanager
    container_name: NewTemplatemanager_Api_Container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5051:8080"
      - "5052:8081"
    # volumes:
    #   - .:/app
    # working_dir: /app
    # environment:
    #   - NODE_ENV=development
    depends_on:
      - NewTemplatemanager_DataBase

  NewTemplatemanager_DataBase:
    image: mysql:8.0
    container_name: NewTemplatemanager_DataBase_Container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Ranti
      MYSQL_DATABASE: NewTemplatemanagerDB
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    

volumes:
  db_data: